# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2019
    env:
      Solution_Name: Applications\WebApplication1\WebApplication1.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path:  Applications\WebApplication1\WebApplication1.csproj                # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

      Wap_Project_Path:  Applications\WebApplication1\WebApplication1.csproj  
      
    steps:
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
